# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.cache/wt [current_project]
set_property parent.project_path /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.6 [current_project]
set_property ip_output_repo /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/hdl/blkEth_wrapper.v
add_files /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/blkEth.bd
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mig_7series_0_2/blkEth_mig_7series_0_2/user_design/constraints/blkEth_mig_7series_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mig_7series_0_2/blkEth_mig_7series_0_2/user_design/constraints/blkEth_mig_7series_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mig_7series_0_2/blkEth_mig_7series_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_4/bd_4e4d_0_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_5/bd_4e4d_0_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_6/bd_4e4d_0_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_7/bd_4e4d_0_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_8/bd_4e4d_0_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_12/bd_4e4d_0_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_13/bd_4e4d_0_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_14/bd_4e4d_0_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_15/bd_4e4d_0_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_16/bd_4e4d_0_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_17/bd_4e4d_0_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_18/bd_4e4d_0_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_19/bd_4e4d_0_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_20/bd_4e4d_0_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_21/bd_4e4d_0_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_22/bd_4e4d_0_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_23/bd_4e4d_0_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_25/bd_4e4d_0_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_26/bd_4e4d_0_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_27/bd_4e4d_0_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_28/bd_4e4d_0_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_29/bd_4e4d_0_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_30/bd_4e4d_0_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_32/bd_4e4d_0_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_33/bd_4e4d_0_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_34/bd_4e4d_0_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_35/bd_4e4d_0_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_36/bd_4e4d_0_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_37/bd_4e4d_0_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_39/bd_4e4d_0_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_40/bd_4e4d_0_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_41/bd_4e4d_0_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_42/bd_4e4d_0_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_43/bd_4e4d_0_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_44/bd_4e4d_0_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_46/bd_4e4d_0_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_47/bd_4e4d_0_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_48/bd_4e4d_0_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_49/bd_4e4d_0_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_50/bd_4e4d_0_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_51/bd_4e4d_0_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_53/bd_4e4d_0_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_54/bd_4e4d_0_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_55/bd_4e4d_0_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_56/bd_4e4d_0_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_57/bd_4e4d_0_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_58/bd_4e4d_0_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_rst_mig_7series_0_200M_1/blkEth_rst_mig_7series_0_200M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_rst_mig_7series_0_200M_1/blkEth_rst_mig_7series_0_200M_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_rst_mig_7series_0_200M_1/blkEth_rst_mig_7series_0_200M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_uartlite_0_0/blkEth_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_uartlite_0_0/blkEth_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_uartlite_0_0/blkEth_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_intc_0_0/blkEth_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_intc_0_0/blkEth_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_intc_0_0/blkEth_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_0/bd_26a2_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_0/synth/bd_26a2_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_0/bd_26a2_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_26a2_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_26a2_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_26a2_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/synth/bd_26a2_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_2/bd_26a2_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_3/bd_26a2_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/bd_26a2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/synth/blkEth_axi_ethernet_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_fifo_1/blkEth_axi_ethernet_0_fifo_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_gtxclk_0/blkEth_axi_ethernet_0_gtxclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_gtxclk_0/blkEth_axi_ethernet_0_gtxclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_gtxclk_0/blkEth_axi_ethernet_0_gtxclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_microblaze_0_1/blkEth_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_microblaze_0_1/blkEth_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_microblaze_0_1/blkEth_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_dlmb_v10_7/blkEth_dlmb_v10_7.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_dlmb_v10_7/blkEth_dlmb_v10_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_ilmb_v10_7/blkEth_ilmb_v10_7.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_ilmb_v10_7/blkEth_ilmb_v10_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_dlmb_bram_if_cntlr_7/blkEth_dlmb_bram_if_cntlr_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_ilmb_bram_if_cntlr_7/blkEth_ilmb_bram_if_cntlr_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_lmb_bram_7/blkEth_lmb_bram_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_timer_0_0/blkEth_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_timer_0_0/blkEth_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/blkEth_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_microblaze_0_1/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top blkEth_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef blkEth_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file blkEth_wrapper_utilization_synth.rpt -pb blkEth_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
