# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/blkEth/blkEth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth || ORIG_REF_NAME==blkEth} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_mdm_1_6 || ORIG_REF_NAME==blkEth_mdm_1_6} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_mig_7series_0_2/blkEth_mig_7series_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_mig_7series_0_2 || ORIG_REF_NAME==blkEth_mig_7series_0_2} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_smc_1/blkEth_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_smc_1 || ORIG_REF_NAME==blkEth_axi_smc_1} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_rst_mig_7series_0_200M_1/blkEth_rst_mig_7series_0_200M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_rst_mig_7series_0_200M_1 || ORIG_REF_NAME==blkEth_rst_mig_7series_0_200M_1} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_uartlite_0_0/blkEth_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_uartlite_0_0 || ORIG_REF_NAME==blkEth_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_intc_0_0/blkEth_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_intc_0_0 || ORIG_REF_NAME==blkEth_axi_intc_0_0} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_ethernet_0_2 || ORIG_REF_NAME==blkEth_axi_ethernet_0_2} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_ethernet_0_fifo_1/blkEth_axi_ethernet_0_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_ethernet_0_fifo_1 || ORIG_REF_NAME==blkEth_axi_ethernet_0_fifo_1} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_ethernet_0_gtxclk_0/blkEth_axi_ethernet_0_gtxclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_ethernet_0_gtxclk_0 || ORIG_REF_NAME==blkEth_axi_ethernet_0_gtxclk_0} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_xlconcat_0_0/blkEth_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_xlconcat_0_0 || ORIG_REF_NAME==blkEth_xlconcat_0_0} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_microblaze_0_1/blkEth_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_microblaze_0_1 || ORIG_REF_NAME==blkEth_microblaze_0_1} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_dlmb_v10_7/blkEth_dlmb_v10_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_dlmb_v10_7 || ORIG_REF_NAME==blkEth_dlmb_v10_7} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_ilmb_v10_7/blkEth_ilmb_v10_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_ilmb_v10_7 || ORIG_REF_NAME==blkEth_ilmb_v10_7} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_dlmb_bram_if_cntlr_7/blkEth_dlmb_bram_if_cntlr_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_dlmb_bram_if_cntlr_7 || ORIG_REF_NAME==blkEth_dlmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_ilmb_bram_if_cntlr_7/blkEth_ilmb_bram_if_cntlr_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_ilmb_bram_if_cntlr_7 || ORIG_REF_NAME==blkEth_ilmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_lmb_bram_7/blkEth_lmb_bram_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_lmb_bram_7 || ORIG_REF_NAME==blkEth_lmb_bram_7} -quiet] -quiet

# IP: bd/blkEth/ip/blkEth_axi_timer_0_0/blkEth_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkEth_axi_timer_0_0 || ORIG_REF_NAME==blkEth_axi_timer_0_0} -quiet] -quiet

# XDC: bd/blkEth/blkEth_ooc.xdc
