# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/eth0/eth0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0 || ORIG_REF_NAME==eth0} -quiet] -quiet

# IP: bd/eth0/ip/eth0_mig_7series_0_0_2/eth0_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_mig_7series_0_0 || ORIG_REF_NAME==eth0_mig_7series_0_0} -quiet] -quiet

# IP: bd/eth0/ip/eth0_microblaze_0_0/eth0_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_microblaze_0_0 || ORIG_REF_NAME==eth0_microblaze_0_0} -quiet] -quiet

# IP: bd/eth0/ip/eth0_dlmb_v10_1/eth0_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_dlmb_v10_1 || ORIG_REF_NAME==eth0_dlmb_v10_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_ilmb_v10_1/eth0_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_ilmb_v10_1 || ORIG_REF_NAME==eth0_ilmb_v10_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_dlmb_bram_if_cntlr_1/eth0_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==eth0_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_ilmb_bram_if_cntlr_1/eth0_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==eth0_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_lmb_bram_1/eth0_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_lmb_bram_1 || ORIG_REF_NAME==eth0_lmb_bram_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_microblaze_0_axi_intc_1/eth0_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_microblaze_0_axi_intc_1 || ORIG_REF_NAME==eth0_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_microblaze_0_xlconcat_1/eth0_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_microblaze_0_xlconcat_1 || ORIG_REF_NAME==eth0_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_mdm_1_1/eth0_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_mdm_1_1 || ORIG_REF_NAME==eth0_mdm_1_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_rst_mig_7series_0_200M_1/eth0_rst_mig_7series_0_200M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_rst_mig_7series_0_200M_1 || ORIG_REF_NAME==eth0_rst_mig_7series_0_200M_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_smc_1/eth0_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_smc_1 || ORIG_REF_NAME==eth0_axi_smc_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_timer_0_1/eth0_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_timer_0_1 || ORIG_REF_NAME==eth0_axi_timer_0_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_uartlite_0_1/eth0_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_uartlite_0_1 || ORIG_REF_NAME==eth0_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_ethernet_0_1 || ORIG_REF_NAME==eth0_axi_ethernet_0_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_ethernet_0_dma_1/eth0_axi_ethernet_0_dma_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_ethernet_0_dma_1 || ORIG_REF_NAME==eth0_axi_ethernet_0_dma_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_axi_ethernet_0_gtxclk_1/eth0_axi_ethernet_0_gtxclk_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_axi_ethernet_0_gtxclk_1 || ORIG_REF_NAME==eth0_axi_ethernet_0_gtxclk_1} -quiet] -quiet

# IP: bd/eth0/ip/eth0_rst_mig_7series_0_100M_1/eth0_rst_mig_7series_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth0_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==eth0_rst_mig_7series_0_100M_1} -quiet] -quiet

# XDC: bd/eth0/eth0_ooc.xdc
