# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.cache/wt [current_project]
set_property parent.project_path /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.6 [current_project]
set_property ip_output_repo /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/hdl/eth0_wrapper.v
add_files /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/eth0.bd
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_mig_7series_0_0_2/eth0_mig_7series_0_0/user_design/constraints/eth0_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_mig_7series_0_0_2/eth0_mig_7series_0_0/user_design/constraints/eth0_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_mig_7series_0_0_2/eth0_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_0/eth0_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_0/eth0_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_0/eth0_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_dlmb_v10_1/eth0_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_dlmb_v10_1/eth0_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_ilmb_v10_1/eth0_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_ilmb_v10_1/eth0_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_dlmb_bram_if_cntlr_1/eth0_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_ilmb_bram_if_cntlr_1/eth0_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_lmb_bram_1/eth0_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_axi_intc_1/eth0_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_axi_intc_1/eth0_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_axi_intc_1/eth0_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_mdm_1_1/eth0_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_mdm_1_1/eth0_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_200M_1/eth0_rst_mig_7series_0_200M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_200M_1/eth0_rst_mig_7series_0_200M_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_200M_1/eth0_rst_mig_7series_0_200M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_1/bd_1b3e_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_1/bd_1b3e_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_2/bd_1b3e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_2/bd_1b3e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_3/bd_1b3e_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_3/bd_1b3e_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_4/bd_1b3e_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_5/bd_1b3e_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_6/bd_1b3e_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_7/bd_1b3e_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_8/bd_1b3e_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_12/bd_1b3e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_13/bd_1b3e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_14/bd_1b3e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_18/bd_1b3e_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_19/bd_1b3e_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_20/bd_1b3e_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_21/bd_1b3e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_22/bd_1b3e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_23/bd_1b3e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_27/bd_1b3e_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_28/bd_1b3e_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_29/bd_1b3e_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_30/bd_1b3e_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_31/bd_1b3e_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_32/bd_1b3e_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_36/bd_1b3e_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_37/bd_1b3e_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_38/bd_1b3e_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_42/bd_1b3e_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_43/bd_1b3e_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_44/bd_1b3e_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_45/bd_1b3e_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_49/bd_1b3e_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_50/bd_1b3e_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_51/bd_1b3e_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_52/bd_1b3e_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_53/bd_1b3e_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_54/bd_1b3e_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_55/bd_1b3e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_56/bd_1b3e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_57/bd_1b3e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_58/bd_1b3e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_59/bd_1b3e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_60/bd_1b3e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_62/bd_1b3e_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_63/bd_1b3e_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_64/bd_1b3e_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_65/bd_1b3e_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_66/bd_1b3e_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_67/bd_1b3e_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_69/bd_1b3e_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_70/bd_1b3e_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_71/bd_1b3e_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_72/bd_1b3e_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_73/bd_1b3e_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_74/bd_1b3e_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_76/bd_1b3e_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_77/bd_1b3e_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_78/bd_1b3e_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_79/bd_1b3e_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_80/bd_1b3e_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_81/bd_1b3e_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_83/bd_1b3e_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_84/bd_1b3e_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_85/bd_1b3e_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_86/bd_1b3e_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_87/bd_1b3e_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_88/bd_1b3e_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_90/bd_1b3e_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_91/bd_1b3e_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_92/bd_1b3e_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_93/bd_1b3e_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_94/bd_1b3e_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/bd_0/ip/ip_95/bd_1b3e_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_timer_0_1/eth0_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_timer_0_1/eth0_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_uartlite_0_1/eth0_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_uartlite_0_1/eth0_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_uartlite_0_1/eth0_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_0/bd_e5ac_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_0/synth/bd_e5ac_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_0/bd_e5ac_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_e5ac_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_e5ac_mac_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_e5ac_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/synth/bd_e5ac_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_2/bd_e5ac_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_3/bd_e5ac_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/bd_e5ac_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/synth/eth0_axi_ethernet_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_dma_1/eth0_axi_ethernet_0_dma_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_dma_1/eth0_axi_ethernet_0_dma_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_dma_1/eth0_axi_ethernet_0_dma_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_gtxclk_1/eth0_axi_ethernet_0_gtxclk_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_gtxclk_1/eth0_axi_ethernet_0_gtxclk_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_gtxclk_1/eth0_axi_ethernet_0_gtxclk_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_100M_1/eth0_rst_mig_7series_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_100M_1/eth0_rst_mig_7series_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_rst_mig_7series_0_100M_1/eth0_rst_mig_7series_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/eth0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top eth0_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth0_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth0_wrapper_utilization_synth.rpt -pb eth0_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
