# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hwBlk/hwBlk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk || ORIG_REF_NAME==hwBlk} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_microblaze_0_0/hwBlk_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_microblaze_0_0 || ORIG_REF_NAME==hwBlk_microblaze_0_0} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_axi_timer_0_0/hwBlk_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_axi_timer_0_0 || ORIG_REF_NAME==hwBlk_axi_timer_0_0} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_axi_uartlite_0_1/hwBlk_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_axi_uartlite_0_1 || ORIG_REF_NAME==hwBlk_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_axi_gpio_0_1/hwBlk_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_axi_gpio_0_1 || ORIG_REF_NAME==hwBlk_axi_gpio_0_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_vio_0_1/hwBlk_vio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_vio_0_1 || ORIG_REF_NAME==hwBlk_vio_0_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_dlmb_v10_1/hwBlk_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_dlmb_v10_1 || ORIG_REF_NAME==hwBlk_dlmb_v10_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_ilmb_v10_1/hwBlk_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_ilmb_v10_1 || ORIG_REF_NAME==hwBlk_ilmb_v10_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_dlmb_bram_if_cntlr_1/hwBlk_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==hwBlk_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_ilmb_bram_if_cntlr_1/hwBlk_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==hwBlk_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_lmb_bram_1/hwBlk_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_lmb_bram_1 || ORIG_REF_NAME==hwBlk_lmb_bram_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_xbar_1/hwBlk_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_xbar_1 || ORIG_REF_NAME==hwBlk_xbar_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_microblaze_0_axi_periph_1/hwBlk_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_microblaze_0_axi_periph_1 || ORIG_REF_NAME==hwBlk_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_microblaze_0_axi_intc_1/hwBlk_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_microblaze_0_axi_intc_1 || ORIG_REF_NAME==hwBlk_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_microblaze_0_xlconcat_1/hwBlk_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_microblaze_0_xlconcat_1 || ORIG_REF_NAME==hwBlk_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_mdm_1_1/hwBlk_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_mdm_1_1 || ORIG_REF_NAME==hwBlk_mdm_1_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_clk_wiz_1_1 || ORIG_REF_NAME==hwBlk_clk_wiz_1_1} -quiet] -quiet

# IP: bd/hwBlk/ip/hwBlk_rst_clk_wiz_1_100M_1/hwBlk_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwBlk_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==hwBlk_rst_clk_wiz_1_100M_1} -quiet] -quiet

# XDC: bd/hwBlk/hwBlk_ooc.xdc
