# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/becario/ethernet/proj/microBase/microBase.cache/wt [current_project]
set_property parent.project_path /home/becario/ethernet/proj/microBase/microBase.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.6 [current_project]
set_property ip_output_repo /home/becario/ethernet/proj/microBase/microBase.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/hdl/hwBlk_wrapper.v
add_files /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/hwBlk.bd
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_0/hwBlk_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_0/hwBlk_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_0/hwBlk_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_timer_0_0/hwBlk_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_timer_0_0/hwBlk_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_uartlite_0_1/hwBlk_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_uartlite_0_1/hwBlk_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_uartlite_0_1/hwBlk_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_gpio_0_1/hwBlk_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_gpio_0_1/hwBlk_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_axi_gpio_0_1/hwBlk_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_vio_0_1/hwBlk_vio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_vio_0_1/hwBlk_vio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_dlmb_v10_1/hwBlk_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_dlmb_v10_1/hwBlk_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_ilmb_v10_1/hwBlk_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_ilmb_v10_1/hwBlk_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_dlmb_bram_if_cntlr_1/hwBlk_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_ilmb_bram_if_cntlr_1/hwBlk_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_lmb_bram_1/hwBlk_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_xbar_1/hwBlk_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_axi_intc_1/hwBlk_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_axi_intc_1/hwBlk_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_axi_intc_1/hwBlk_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_mdm_1_1/hwBlk_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_mdm_1_1/hwBlk_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_rst_clk_wiz_1_100M_1/hwBlk_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_rst_clk_wiz_1_100M_1/hwBlk_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_rst_clk_wiz_1_100M_1/hwBlk_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/hwBlk_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/becario/ethernet/proj/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hwBlk_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hwBlk_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hwBlk_wrapper_utilization_synth.rpt -pb hwBlk_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
