# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xci
# IP: The module: 'hwBlk_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xci
# IP: The module: 'hwBlk_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/microBase/microBase.srcs/sources_1/bd/hwBlk/ip/hwBlk_clk_wiz_1_1/hwBlk_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hwBlk_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
