# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xci
# IP: The module: 'blkEth_mdm_1_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_mdm_1_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_mdm_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xci
# IP: The module: 'blkEth_mdm_1_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_mdm_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_mdm_1_6/blkEth_mdm_1_6_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_mdm_1_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
