# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2.xci
# IP: The module: 'blkEth_axi_ethernet_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/bd_26a2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2 || ORIG_REF_NAME==bd_26a2} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_0/bd_26a2_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_eth_buf_0 || ORIG_REF_NAME==bd_26a2_eth_buf_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/bd_26a2_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_mac_0 || ORIG_REF_NAME==bd_26a2_mac_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_2/bd_26a2_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_c_shift_ram_0_0 || ORIG_REF_NAME==bd_26a2_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_3/bd_26a2_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_c_counter_binary_0_0 || ORIG_REF_NAME==bd_26a2_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_4/bd_26a2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_xlconstant_0_0 || ORIG_REF_NAME==bd_26a2_xlconstant_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_5/bd_26a2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_util_vector_logic_0_0 || ORIG_REF_NAME==bd_26a2_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/bd_26a2_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/synth/blkEth_axi_ethernet_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2.xci
# IP: The module: 'blkEth_axi_ethernet_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/bd_26a2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2 || ORIG_REF_NAME==bd_26a2} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_0/bd_26a2_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_eth_buf_0 || ORIG_REF_NAME==bd_26a2_eth_buf_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_1/bd_26a2_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_mac_0 || ORIG_REF_NAME==bd_26a2_mac_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_2/bd_26a2_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_c_shift_ram_0_0 || ORIG_REF_NAME==bd_26a2_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_3/bd_26a2_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_c_counter_binary_0_0 || ORIG_REF_NAME==bd_26a2_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_4/bd_26a2_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_xlconstant_0_0 || ORIG_REF_NAME==bd_26a2_xlconstant_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/ip/ip_5/bd_26a2_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_26a2_util_vector_logic_0_0 || ORIG_REF_NAME==bd_26a2_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/bd_0/bd_26a2_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/blkEth_axi_ethernet_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_ethernet_0_2/synth/blkEth_axi_ethernet_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_ethernet_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
