# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1.xci
# IP: The module: 'eth0_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/bd_e5ac.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac || ORIG_REF_NAME==bd_e5ac} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_0/bd_e5ac_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_eth_buf_0 || ORIG_REF_NAME==bd_e5ac_eth_buf_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/bd_e5ac_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_mac_0 || ORIG_REF_NAME==bd_e5ac_mac_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_2/bd_e5ac_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_c_shift_ram_0_0 || ORIG_REF_NAME==bd_e5ac_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_3/bd_e5ac_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_c_counter_binary_0_0 || ORIG_REF_NAME==bd_e5ac_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_4/bd_e5ac_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_xlconstant_0_0 || ORIG_REF_NAME==bd_e5ac_xlconstant_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_5/bd_e5ac_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_util_vector_logic_0_0 || ORIG_REF_NAME==bd_e5ac_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/bd_e5ac_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth0_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/synth/eth0_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth0_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1.xci
# IP: The module: 'eth0_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/bd_e5ac.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac || ORIG_REF_NAME==bd_e5ac} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_0/bd_e5ac_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_eth_buf_0 || ORIG_REF_NAME==bd_e5ac_eth_buf_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_1/bd_e5ac_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_mac_0 || ORIG_REF_NAME==bd_e5ac_mac_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_2/bd_e5ac_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_c_shift_ram_0_0 || ORIG_REF_NAME==bd_e5ac_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_3/bd_e5ac_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_c_counter_binary_0_0 || ORIG_REF_NAME==bd_e5ac_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_4/bd_e5ac_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_xlconstant_0_0 || ORIG_REF_NAME==bd_e5ac_xlconstant_0_0} -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/ip/ip_5/bd_e5ac_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e5ac_util_vector_logic_0_0 || ORIG_REF_NAME==bd_e5ac_util_vector_logic_0_0} -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/bd_0/bd_e5ac_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/eth0_axi_ethernet_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth0_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/eth0/ip/eth0_axi_ethernet_0_1/synth/eth0_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth0_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
