# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/blkEth_axi_smc_1.xci
# IP: The module: 'blkEth_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/bd_4e4d_0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_0/bd_4e4d_0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_4/bd_4e4d_0_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_5/bd_4e4d_0_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_6/bd_4e4d_0_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_7/bd_4e4d_0_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_8/bd_4e4d_0_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_9/bd_4e4d_0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_10/bd_4e4d_0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_11/bd_4e4d_0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_12/bd_4e4d_0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_13/bd_4e4d_0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_14/bd_4e4d_0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_15/bd_4e4d_0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_16/bd_4e4d_0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_17/bd_4e4d_0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_18/bd_4e4d_0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_19/bd_4e4d_0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_20/bd_4e4d_0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_21/bd_4e4d_0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_22/bd_4e4d_0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_23/bd_4e4d_0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_24/bd_4e4d_0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_25/bd_4e4d_0_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_26/bd_4e4d_0_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_27/bd_4e4d_0_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_28/bd_4e4d_0_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_29/bd_4e4d_0_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_30/bd_4e4d_0_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_31/bd_4e4d_0_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_32/bd_4e4d_0_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_33/bd_4e4d_0_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_34/bd_4e4d_0_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_35/bd_4e4d_0_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_36/bd_4e4d_0_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_37/bd_4e4d_0_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_38/bd_4e4d_0_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_39/bd_4e4d_0_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_40/bd_4e4d_0_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_41/bd_4e4d_0_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_42/bd_4e4d_0_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_43/bd_4e4d_0_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_44/bd_4e4d_0_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_45/bd_4e4d_0_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_46/bd_4e4d_0_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_47/bd_4e4d_0_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_48/bd_4e4d_0_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_49/bd_4e4d_0_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_50/bd_4e4d_0_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_51/bd_4e4d_0_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_52/bd_4e4d_0_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_53/bd_4e4d_0_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_54/bd_4e4d_0_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_55/bd_4e4d_0_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_56/bd_4e4d_0_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_57/bd_4e4d_0_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_58/bd_4e4d_0_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_59/bd_4e4d_0_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_4/bd_4e4d_0_arsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_5/bd_4e4d_0_rsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_6/bd_4e4d_0_awsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_7/bd_4e4d_0_wsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_8/bd_4e4d_0_bsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_12/bd_4e4d_0_s00a2s_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_13/bd_4e4d_0_sarn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_14/bd_4e4d_0_srn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_15/bd_4e4d_0_sawn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_16/bd_4e4d_0_swn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_17/bd_4e4d_0_sbn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_18/bd_4e4d_0_m00s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_19/bd_4e4d_0_m00arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_20/bd_4e4d_0_m00rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_21/bd_4e4d_0_m00awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_22/bd_4e4d_0_m00wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_23/bd_4e4d_0_m00bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_25/bd_4e4d_0_m01s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_26/bd_4e4d_0_m01arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_27/bd_4e4d_0_m01rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_28/bd_4e4d_0_m01awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_29/bd_4e4d_0_m01wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_30/bd_4e4d_0_m01bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_32/bd_4e4d_0_m02s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_33/bd_4e4d_0_m02arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_34/bd_4e4d_0_m02rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_35/bd_4e4d_0_m02awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_36/bd_4e4d_0_m02wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_37/bd_4e4d_0_m02bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_39/bd_4e4d_0_m03s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_40/bd_4e4d_0_m03arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_41/bd_4e4d_0_m03rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_42/bd_4e4d_0_m03awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_43/bd_4e4d_0_m03wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_44/bd_4e4d_0_m03bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_46/bd_4e4d_0_m04s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_47/bd_4e4d_0_m04arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_48/bd_4e4d_0_m04rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_49/bd_4e4d_0_m04awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_50/bd_4e4d_0_m04wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_51/bd_4e4d_0_m04bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_53/bd_4e4d_0_m05s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_54/bd_4e4d_0_m05arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_55/bd_4e4d_0_m05rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_56/bd_4e4d_0_m05awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_57/bd_4e4d_0_m05wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_58/bd_4e4d_0_m05bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/blkEth_axi_smc_1.xci
# IP: The module: 'blkEth_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/bd_4e4d_0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_0/bd_4e4d_0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_4/bd_4e4d_0_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_5/bd_4e4d_0_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_6/bd_4e4d_0_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_7/bd_4e4d_0_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_8/bd_4e4d_0_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_9/bd_4e4d_0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_10/bd_4e4d_0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_11/bd_4e4d_0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_12/bd_4e4d_0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_13/bd_4e4d_0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_14/bd_4e4d_0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_15/bd_4e4d_0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_16/bd_4e4d_0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_17/bd_4e4d_0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_18/bd_4e4d_0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_19/bd_4e4d_0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_20/bd_4e4d_0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_21/bd_4e4d_0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_22/bd_4e4d_0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_23/bd_4e4d_0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_24/bd_4e4d_0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_25/bd_4e4d_0_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_26/bd_4e4d_0_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_27/bd_4e4d_0_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_28/bd_4e4d_0_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_29/bd_4e4d_0_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_30/bd_4e4d_0_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_31/bd_4e4d_0_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_32/bd_4e4d_0_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_33/bd_4e4d_0_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_34/bd_4e4d_0_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_35/bd_4e4d_0_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_36/bd_4e4d_0_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_37/bd_4e4d_0_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_38/bd_4e4d_0_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_39/bd_4e4d_0_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_40/bd_4e4d_0_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_41/bd_4e4d_0_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_42/bd_4e4d_0_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_43/bd_4e4d_0_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_44/bd_4e4d_0_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_45/bd_4e4d_0_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_46/bd_4e4d_0_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_47/bd_4e4d_0_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_48/bd_4e4d_0_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_49/bd_4e4d_0_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_50/bd_4e4d_0_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_51/bd_4e4d_0_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_52/bd_4e4d_0_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_53/bd_4e4d_0_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_54/bd_4e4d_0_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_55/bd_4e4d_0_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_56/bd_4e4d_0_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_57/bd_4e4d_0_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_58/bd_4e4d_0_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_59/bd_4e4d_0_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_1/bd_4e4d_0_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_2/bd_4e4d_0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_3/bd_4e4d_0_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_4/bd_4e4d_0_arsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_5/bd_4e4d_0_rsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_6/bd_4e4d_0_awsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_7/bd_4e4d_0_wsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_8/bd_4e4d_0_bsw_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_12/bd_4e4d_0_s00a2s_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_13/bd_4e4d_0_sarn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_14/bd_4e4d_0_srn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_15/bd_4e4d_0_sawn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_16/bd_4e4d_0_swn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_17/bd_4e4d_0_sbn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_18/bd_4e4d_0_m00s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_19/bd_4e4d_0_m00arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_20/bd_4e4d_0_m00rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_21/bd_4e4d_0_m00awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_22/bd_4e4d_0_m00wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_23/bd_4e4d_0_m00bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_25/bd_4e4d_0_m01s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_26/bd_4e4d_0_m01arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_27/bd_4e4d_0_m01rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_28/bd_4e4d_0_m01awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_29/bd_4e4d_0_m01wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_30/bd_4e4d_0_m01bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_32/bd_4e4d_0_m02s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_33/bd_4e4d_0_m02arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_34/bd_4e4d_0_m02rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_35/bd_4e4d_0_m02awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_36/bd_4e4d_0_m02wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_37/bd_4e4d_0_m02bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_39/bd_4e4d_0_m03s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_40/bd_4e4d_0_m03arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_41/bd_4e4d_0_m03rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_42/bd_4e4d_0_m03awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_43/bd_4e4d_0_m03wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_44/bd_4e4d_0_m03bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_46/bd_4e4d_0_m04s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_47/bd_4e4d_0_m04arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_48/bd_4e4d_0_m04rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_49/bd_4e4d_0_m04awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_50/bd_4e4d_0_m04wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_51/bd_4e4d_0_m04bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_53/bd_4e4d_0_m05s2a_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_54/bd_4e4d_0_m05arn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_55/bd_4e4d_0_m05rn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_56/bd_4e4d_0_m05awn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_57/bd_4e4d_0_m05wn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/bd_0/ip/ip_58/bd_4e4d_0_m05bn_0_ooc.xdc

# XDC: /home/becario/ethernet/proj/noSeasCulia/noSeasCulia.srcs/sources_1/bd/blkEth/ip/blkEth_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blkEth_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
